name: Bearer

on:
  push:
    branches: [$default-branch, $protected-branches]
  pull_request:
    branches: [$default-branch]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/checkout@v4

      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: results.sarif
          exit-code: 0

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
